geiot/urls.py
from django.urls import path
from django.conf import settings
from . import views


# アプリ名を記述
app_name = 'geiot'

# ここの配列の中にルーティングを書いていきます。
urlpatterns = [
  path('', views.index, name="index"),
  path('result', views.result, name="result"),
  path('select', views.select, name="select"),
  path('test', views.test, name="test"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('geiot.urls'))
]

geiot/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    
    text = models.TextField()
    memo = models.TextField()


    #def publish(self):
        #self.published_date = timezone.now()
        #self.save()

    #def __str__(self):
        #return self.title

geiot/views.py
from django.shortcuts import render
# Create your views here.

def index(request):
  return render(request, 'geiot/index.html')

def result(request):
  return render(request, 'geiot/result.html')

def select(request):
  return render(request, 'geiot/select.html')

def test(request):
  return render(request, 'geiot/test.html')

templates/geiot/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>prAIse</title>

    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link ref="stylesheet" href="https://fonts.googleapis.com/css?family=Philosopher">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

  <body>
    <div id="home" class="big-bg">
      <header class="page-header wrapper">
        <h1><a href="{% url 'geiot:index' %}"><img class="logo" src="{% static 'image/logo.png' %}" alt="prAIse ホーム"></a><h1>
        <nav>
          <ul class="main-nav">
            <li><a href="">求人一覧</a></li>
            <li><a href="">ステータス</a></li>
            <li><a href="">Web テスト</a></li> 
          </ul>
        </nav>
      </header>

      <div class="home-content wrapper">
        <h2 class="page-title">prAIse</h2>
        <p>機械学習人材スキルチェックサービス</p>
        <a class="button" href="{% url 'geiot:select' %}">テストを受ける</a>
      </div><!-- /.home-content -->
    </div><!-- /#home --> 

    <div class="service">
      <h2><span>サービス紹介</span></h2>
    </div>
    
    <div class="wrapper service-grid">
      <div class="item">
        <img src="{% static 'image/recruit.jpg' %}" alt="">
        <h3>コードで採用</h3>
        <p>プログラミングスキルがあればES選考なしで企業に応募ができるITエンジニアを目指す人のための就職サービスです.</p>
      </div>
      <div class="item">
        <img src="{% static 'image/learning.jpg' %}" alt="">
        <h3>prAIse ラーニング</h3>
        <p>prAIseラーニングは、オンラインでプログラミングしながらスキルアップできるプログラミング入門学習コンテンツです。</p>
      </div>
    </div>

    <div class="job">
      <h2><span>新着求人</span></h2>
    </div>
    
    <div class="wrapper job-grid">
      <div class="item">
        <img src="{% static 'image/hoogle.jpg' %}" alt="">
        <h3>Hoogle</h3>
        <p>世界最大級のウェブ検索エンジンを提供する企業です．</p>
      </div>
      <div class="item">
        <img src="{% static 'image/disco.jpg' %}" alt="">
        <h3>Disco</h3>
        <p>ネットワーク機器の製造販売を行う世界シェア最大級の企業です．</p>
      </div>
      <div class="item">
        <img src="{% static 'image/bamazon.jpg' %}" alt="">
        <h3>Bamazon</h3>
        <p>世界最大級のEコマース・プラットフォームを提供する企業です．</p>
      </div>
      <div class="item">
        <img src="{% static 'image/nicrosoft.jpg' %}" alt="">
        <h3>Nicrosoft</h3>
        <p>オペレーティング・システムの開発・販売を行う世界シェア最大級の企業です．</p>
      </div>
      <div class="item">
        <img src="{% static 'image/metflix.jpg' %}" alt="">
        <h3>Metflix</h3>
        <p>動画配信サービス世界シェア最大級の企業です．</p>
      </div>
      <div class="item">
        <img src="{% static 'image/gacebook.jpg' %}" alt="">
        <h3>Gacebook</h3>
        <p>Gacebook や Enstagram をグループに抱える SNS 業界のジャイアントです． </p>
      </div>
    </div>
  </body>

  <footer>
    <div class="footer">
      <p><small>&copy; 2020 チーム・ドードリオ</small></p>
    </div>
  </footer>

</html>

templates/geiot/result.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>prAIse - RESULT</title>

    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link ref="stylesheet" href="https://fonts.googleapis.com/css?family=Philosopher">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  </head>

  <body>
    <div id="result" class="big-bg">
      <header class="page-header wrapper">
        <h1><a href="{% url 'geiot:index' %}"><img class="logo" src="{% static 'image/logo.png' %}" alt="prAIse ホーム"></a><h1>
        <nav>
          <ul class="main-nav">
            <li><a href="">求人一覧</a></li>
            <li><a href="">ステータス</a></li>
            <li><a href="">Web テスト</a></li> 
          </ul>
        </nav>
      </header>

      <div class="wrapper">
        <h2 class="page-title">Result</h2>
      </div><!-- /.wrapper -->
    </div>

    <div class="wrapper">
      <table class="table table-hover table-striped">
        <thead class="thead-light">
          <tr>
            <th scope="col">#  of Test</th>
            <th scope="col"># of Case</th>
            <th scope="col">Result</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>1</td>
            <td><div class="passed">○ Passed</div></td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>1</td>
            <td><div class="passed">○ Passed</div></td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>1</td>
            <td><div class="passed">○ Passed</div></td>
          <tr>
            <th scope="row">4</th>
            <td>1</td>
            <td><div class="rejected">× Rejected</div></td>
          </tr>
          <tr>
            <th scope="row">5</th>
            <td>1</td>
            <td><div class="passed">○ Passed</div></td>
          </tr>
          <tr>
            <th scope="row">6</th>
            <td>1</td>
            <td><div class="passed">○ Passed</div></td>
          </tr>
          <tr>
            <th scope="row">7</th>
            <td>1</td>
            <td><div class="passed">○ Passed</div></td>
          </tr>
          <tr>
            <th scope="row">8</th>
            <td>1</td>
            <td><div class="passed">○ Passed</div></td>
          <tr>
            <th scope="row">9</th>
            <td>1</td>
            <td><div class="rejected">× Rejected</div></td>
          </tr>
          <tr>
            <th scope="row">10</th>
            <td>1</td>
            <td><div class="passed">○ Passed</div></td>
          </tr>
        </tbody>
      </table>
      <br>
       <center><a class="button-submit" href="{% url 'geiot:index' %}">終了する</a></center>
    </div>


  </body>

  <footer>
    <div class="footer">
      <p><small>&copy; 2020 チーム・ドードリオ</small></p>
    </div>
  </footer>

</html>

templates/geiot/select.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>prAIse - SELECT</title>

    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link ref="stylesheet" href="https://fonts.googleapis.com/css?family=Philosopher">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  </head>

  <body>
    <div id="result" class="big-bg">
      <header class="page-header wrapper">
        <h1><a href="{% url 'geiot:index' %}"><img class="logo" src="{% static 'image/logo.png' %}" alt="prAIse ホーム"></a><h1>
        <nav>
          <ul class="main-nav">
            <li><a href="">求人一覧</a></li>
            <li><a href="">ステータス</a></li>
            <li><a href="">Web テスト</a></li> 
          </ul>
        </nav>
      </header>

      <div class="wrapper">
        <h2 class="page-title">Select</h2>
      </div><!-- /.wrapper -->
    </div>

    <div class="wrapper">
     <div class="card">
       <div class="card-header">
         機械学習1
       </div>
       <ul class="select-nav">
        <li>正解率:70%</li>
        <li>制限時間:1時間</li>
        <li>平均回答時間:20分</li> 
        <li><a class="question-button" href="{% url 'geiot:test' %}">テストを受ける</a></li>
       </ul>
     </div>
    
    <br>

    <div class="card">
      <div class="card-header">
        機械学習2
      </div>
      <ul class="select-nav">
       <li>正解率:70%</li>
       <li>制限時間:1時間</li>
       <li>平均回答時間:20分</li> 
       <li><a class="question-button" href="">テストを受ける</a></li>
      </ul>
    </div>
   
    <br>

    <div class="card">
      <div class="card-header">
        機械学習3
      </div>
      <ul class="select-nav">
      <li>正解率:70%</li>
      <li>制限時間:1時間</li>
      <li>平均回答時間:20分</li> 
      <li><a class="question-button" href="">テストを受ける</a></li>
      </ul>
    </div>
 
  <br>

  <div class="card">
    <div class="card-header">
      機械学習4
    </div>
    <ul class="select-nav">
    <li>正解率:70%</li>
    <li>制限時間:1時間</li>
    <li>平均回答時間:20分</li> 
    <li><a class="question-button" href="">テストを受ける</a></li>
    </ul>
  </div>

  <br>

  <div class="card">
    <div class="card-header">
      機械学習5
    </div>
    <ul class="select-nav">
    <li>正解率:70%</li>
    <li>制限時間:1時間</li>
    <li>平均回答時間:20分</li> 
    <li><a class="question-button" href="">テストを受ける</a></li>
    </ul>
  </div>
</div>


    


  </body>

  <footer>
    <div class="footer">
      <p><small>&copy; 2020 チーム・ドードリオ</small></p>
    </div>
  </footer>

</html>

templates/geiot/test.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>prAIse - スキルチェックテスト</title>
    <link rel="stylesheet" href="http://esironal.github.io/cmtouch/lib/codemirror.css">
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link ref="stylesheet" href="https://fonts.googleapis.com/css?family=Philosopher">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  </head>

  <body>
    <div id="result" class="big-bg">
      <header class="page-header wrapper">
        <h1><a href="{% url 'geiot:index' %}"><img class="logo" src="{% static 'image/logo.png' %}" alt="prAIse ホーム"></a><h1>
        <nav>
          <ul class="main-nav">
            <li><a href="">求人一覧</a></li>
            <li><a href="">ステータス</a></li>
            <li><a href="">Web テスト</a></li> 
          </ul>
        </nav>
      </header>

      <div class="wrapper">
        <h2 class="page-title">スキルチェックテスト</h2>
      </div><!-- /.wrapper -->
    </div>

    <div class="wrapper">
      <div class="job"><h2><span>機械学習1</span></h2></div>
      <div class="card">
        <div class="card-header">
          <h3>問題文</h3>
        </div>
        <p>この課題では、リカレントニューラルネットワーク(RNN)の前方伝播を計算します。Table1に入力層、Table2にRNNの出力層を示します。𝑅𝑒𝐿𝑈(𝑎)を活性化関数として与え、RNNモデルをfigのように定義します。また、Table3に重みパラメタの値を記す。時刻t=1のとき、𝑥1を1、その他を0として入力したときの𝑦の予測値を計算せよ。</p>
        <img src="{% static 'image/question.png' %}" alt="">
      </div>
      <br>
      <div class="card">
        <div class="card-header">
            <dev class="title-time"><h3>回答欄</h3><P>制限時間 あと59分</P></dev>
        </div>
        <textarea id="editor_js" rows="30" cols="50">
#!/usr/bin/env python
# coding: utf-8

import numpy as np
from sklearn import datasets
from sklearn import cross_validation
from sklearn import metrics

class MultiLayerPerceptron:
def __init__(self, dim, n_mnodes, n_onodes=1, eta=1, beta=1):
  # expでオーバーフローが発生することがあるがひとまず無視する
  np.seterr(over='ignore')
  np.seterr(divide='raise')
  # 重みベクトルの初期値はランダムなベクトルとする
  self.w = np.random.uniform(-1., 1., (n_mnodes, dim))
  self.v = np.random.uniform(-1., 1., (n_onodes, n_mnodes))
  self.n_mnodes = n_mnodes # 中間層のノード数
  self.n_onodes = n_onodes # 出力層のノード数
  self.eta = eta
  self.beta = beta

# シグモイド関数
def g(self, x):
  return 1.0/(1.0+np.exp(-self.beta*x))

# シグモイド関数の1階導関数
def g_(self, x):
  return self.beta*self.g(x)*(1-self.g(x))

# 入力ベクトルから中間層の出力を得る
def hidden_layer(self, x):
  return np.array([self.g(self.w[m].T.dot(x)) for m in range(self.n_mnodes)])
        </textarea>
      </div>
      <br>
      <center><a class="button-submit" href="{% url 'geiot:result' %}">コード提出</a></center>
    </div>


    


  </body>

  <footer>
    <div class="footer">
      <p><small>&copy; 2020 チーム・ドードリオ</small></p>
    </div>
  </footer>
  <script src="http://esironal.github.io/cmtouch/lib/codemirror.js"></script>
  <script src="http://esironal.github.io/cmtouch/mode/python/python.js"></script>
  <script>
var jsEditor = CodeMirror.fromTextArea(document.getElementById('editor_js'), {
    mode: "python",
    lineNumbers: true,
    indentUnit: 4
});
  </script>
</html>